# Generated by Django 3.2.4 on 2023-11-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interface', models.CharField(max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=20, null=True)),
                ('mask', models.CharField(blank=True, max_length=20, null=True)),
                ('vlan', models.IntegerField(blank=True, null=True)),
                ('is_host', models.BooleanField(default=False)),
            ],
        ),
    ]
