# Generated by Django 3.2.4 on 2023-11-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='firewall',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
